#Test with: http://editor.swagger.io/

swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Authentication
  description: Ruby + MySQL
  license:
    name: Software Architecture 2018-I
host: 192.168.99.101:4003
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/sign_in:
    post:
      summary: Creates a new session user
      operationId: createSeassion
      parameters:
        - name: email, password
          in: body
          required: true
          description: Email y contraseña que tiene registrado el usuario en la aplicación.
          schema:
            $ref: '#/definitions/SessionInput'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Data'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'

definitions:

  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      provider:
        type: string
      uid:
        type: string
      allow_password_change:
        type: boolean
      name:
        type: string
      nickname:
        type: string
      image:
        type: string

  # Sessions
  Data:
    type: object
    properties:
      data:
        type: object
        $ref: '#/definitions/User'

  SessionInput:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

# Errors
  ErrorModel:
    type: object
    properties:
      success:
        type: boolean
      errors:
        type: array
        items:
          type: string