version: '2'
services:
  authentication-db:
    image: mysql:5.7.22
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: arqui
      MYSQL_USER: user
      MYSQL_PASSWORD: arqui
      MYSQL_DATABASE: authentication-db
      MYSQL_HOST: authentication-db
  authentication-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4003 -b '0.0.0.0'"
    depends_on:
      - authentication-db
    ports:
      - '4003:4003'
